apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket.services.discount
  labels:
    version: dev
    product: globoticket.services.discount
spec:
  selector:
    app: globoticket.services.discount
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-services-discount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globoticket-services-discount
  template:
    metadata:
      labels:
        app: globoticket-services-discount
    spec:
      containers:
      - name: globoticket-services-discount
        image: globoticket.azurecr.io/globoticket.services.discount:#{Build.BuildId}#
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__DefaultConnection
          value: Data Source=db;Initial Catalog=GloboTicketDiscountDB;Integrated Security=False;User ID=globoticket-user;Password=P(ssw0rd0123);Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: pullkey
