apiVersion: v1
kind: Service
metadata:
  name: svc-globoticket-gateway-mobilebff
  labels:
    version: dev
    product: globoticket-gateway-mobilebff
spec:
  selector:
    app: globoticket-gateway-mobilebff
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-globoticket-gateway-mobilebff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globoticket-gateway-mobilebff
  template:
    metadata:
      labels:
        app: globoticket-gateway-mobilebff
    spec:
      containers:
      - name: globoticket-gateway-mobilebff
        image: globoticket.azurecr.io/globoticket.gateway.mobilebff:#{Build.BuildId}#
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ApiConfigs__EventCatalog__Uri
          value: http://svc-globoticket-services-eventcatalog
        - name: ApiConfigs__ShoppingBasket__Uri
          value: http://svc-globoticket-services-shoppingbasket
        - name: ApiConfigs__Payment__Uri
          value: http://svc-globoticket-services-payment
        - name: ApiConfigs__Order__Uri
          value: http://svc-globoticket-services-ordering
        - name: ApiConfigs__Marketing__Uri
          value: http://svc-globoticket-services-marketing
        - name: ApiConfigs__Eventcatalog__Uri
          value: http://svc-globoticket-services-eventcatalog
        - name:  ApiConfigs__Discount__Uri
          value: http://svc-globoticket-services-discount
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: pullkey
